### ISSUE TITLE
Alerts not sending to Opsgenie

### ISSUE THREAD

**Issue by pbr0ck3r** [opsgenie/opsgenie-graylog-plugin#1]
Graylog version 2.3.1
Opsgenie version 1.2.1-SNAPSHOT

After setting up inputs, streams, and rules in graylog. I am able to send a test alert for my desired rule. The alert shows in graylog logs.

`com.opsgenie.plugin.graylog.OpsGenieGraylogClient - Successfully sent alert creation request to OpsGenie. Message: Request will be processed RequestId: 2018f75c-c7d9-4619-b440-bb3f663b093a`

When a real alert is fired. I can see the log in the stream and then see the alert, but  no notification/alert is sent to Opsgenie, even when a alert is showing up as triggered. 

I do not see any errors or logs in graylog logs.

Opsgenie 1.2.1-SNAPSHOT was working with graylog version 2.3.0.

**Comment by ufukoz** [comment]
Hi,

We're trying to identify the problem. Just to be sure can you verify that you followed these steps in this [doc](https://docs.opsgenie.com/docs/graylog-integration) when you're setting up your OpsGenie Graylog plugin?

And also if you have any logs regarding your issue could you please share them with us?

Could you also tell us your alert conditions on Graylog? And again just to be sure can you verify that the installation of the plugin was done correctly?

And finally are there any conditions for plugin to fire alerts or does it fire alerts with every alerting situation?

We'll try to reproduce your problem and get back to you.

Regards,

**Comment by pbr0ck3r** [comment]
Yes I am sure Opsegnie is setup correctly. When I use Opsgenie version 1.0.1 alerts work fine. But when I use version 1.2.0 I get `No notifications were configured for this alert` and no alert is triggered in opsgenie. OG version 1.2.0 was working for graylog version 2.3.0 but since it is no longer working on GL 2.3.1 I have rolled back to using OG 1.0.1

**Comment by tnucera** [comment]
Same issue here. 

Graylog 2.3.1
opsgenie-graylog-alarmcallback-1.2.0.jar 

`No notifications were configured for this alert`

'Dummy alert to test notifications' works.

**Comment by ufukoz** [comment]
Hi,

We have a ticket about this issue and we're working on a fix. In the meantime if you can provide us some logs or any other kind of information we'd appreciate it. We'll inform you when it's fixed.

Regards,

**Comment by bcelenk** [comment]
Hi @pbr0ck3r , @tnucera 
We've updated the plugin to work with Graylog 2.3.1. Apparently Graylog dependencies aren't backwards compatible.
