### ISSUE TITLE
Alerts are not being closed in OpsGenie

### ISSUE THREAD

**Issue by ps-beilers** [opsgenie/opsgenie-graylog-plugin#12]
Hello

We've noticed that alerts that are opened in OpsGenie are not automatically resolved inside OpsGenie once the alert clears in Graylog itself. We suspect this is a shortcoming of how Graylog handles alert callbacks and that this is the expected behaviour.

Is this really the case, or should the alerts in OpsGenie close automatically via the plugin?

Thanks,
Bernd

**Comment by cglrkn** [comment]
Hi @ps-beilers,

The integration only supports alert creation. Thus, we can say that it is the expected behavior.

Thanks
