### ISSUE TITLE
opsgenie-graylog intended for a different operating system

### ISSUE THREAD

**Issue by madchap** [opsgenie/opsgenie-graylog-plugin#3]
Hi,

Getting this trying to install opsgenie-graylog-alarmcallback-1.3.0-RELEASE onto a CentOS 7 system:

```
sudo rpm -ivh --test opsgenie-graylog-alarmcallback-1.3.0-1.noarch.rpm
warning: opsgenie-graylog-alarmcallback-1.3.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 4fec4663: NOKEY
Preparing...                          ################################# [100%]
        package opsgenie-graylog-alarmcallback-1.3.0-RELEASE_1.noarch is intended for a different operating system
```

The RPM was built on a mac, and as such, will not install like on this linux.

```
 rpm -qpi opsgenie-graylog-alarmcallback-1.3.0-1.noarch.rpm
warning: opsgenie-graylog-alarmcallback-1.3.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 4fec4663: NOKEY
Name        : opsgenie-graylog-alarmcallback
Version     : 1.3.0
Release     : RELEASE_1
Architecture: noarch
Install Date: (not installed)
Group       : Application/Internet
Size        : 16485
License     : (c) null
Signature   : RSA/SHA1, Wed 18 Oct 2017 06:52:26 AM GMT, Key ID d471f82c4fec4663
Source RPM  : opsgenie-graylog-alarmcallback-1.3.0-RELEASE_1.src.rpm
Build Date  : Wed 18 Oct 2017 06:52:26 AM GMT
Build Host  : Beners-MacBook-Pro.local
Relocations : /usr
Summary     : opsgenie-graylog-alarmcallback
Description :
Graylog opsgenie-graylog-alarmcallback plugin.
```

Please build the rpm for linux, or specific the rpm is for darwin.

Cheers,
fred

**Comment by bcelenk** [comment]
Hi @madchap ,
Thanks for notifying, .rpm and .deb packages are useful to create the plugin.jar in a pre-defined location. This location could be seen in the project's pom as ${graylog.plugin-dir}. You could built your own rpm package to overcome the problem you mentioned. Or you could use `rpm2cpio plugin.rpm | cpio -idmv` to extract the plugin.jar. I'll delete the .rpm and .deb packages from releases.

**Comment by madchap** [comment]
Sure, I am building my own rpms. It was kind of "nice" to see I didn't have to anymore ;-) (but that I still do in fact ;-)).

Cheers.
