### ISSUE TITLE
Error code 406

### ISSUE THREAD

**Issue by tnucera** [opsgenie/opsgenie-graylog-plugin#4]
Hello,

I have an error with the latest versions of Graylog (2.3.2) & OpsGenie plugin (1.3.0):
```
Sending test alert notification failed with message: Error while creating alert at OpsGenie. Response: {"code":406,"message":"Could not find acceptable representation","took":0.001,"requestId":"0cf1718f-6c22-4011-bc8e-ab9074d21fcd"}
```

**Comment by Kebart** [comment]
Same here with Graylog version '2.3.2' & OpsGenie plugin version '1.3.0-RELEASE'

**Comment by bcelenk** [comment]
Hi @tnucera , @Kebart ,
Thanks for your feedback, we've updated our plugin to work with Graylog Version 2.3.2. You may found the new release [1.3.1] under [releases](https://github.com/opsgenie/opsgenie-graylog-plugin/releases).
