### ISSUE TITLE
Fill a new field "Description"

### ISSUE THREAD

**Issue by KevDBG** [opsgenie/opsgenie-graylog-plugin#7]
Hello,

It would be really interesting if we can push a new field "description" from Graylog to OpsGenie.

The purpose is to use the "Description" field provide by the OpsGenie alarm callback directly in the Graylog notification. With that, we can add a custom text in the alert notification like a specific process.

Thank you !

**Comment by cglrkn** [comment]
Hi, I will share this idea with my team. Thanks!
