### ISSUE TITLE
Change the description text when the ticket is opened

### ISSUE THREAD

**Issue by KevDBG** [opsgenie/opsgenie-graylog-plugin#8]
Hello,

Is-it possible to change the description sent from Graylog to Opsgenie ?
Currently graylog send the stream name, is it possible to change it or to add the Graylog notification name ?

It's better, because the stream name is not really important in the alerting.

Thanks a lot,

**Comment by KevDBG** [comment]
Hello,

Handle with the PR  => https://github.com/opsgenie/opsgenie-graylog-plugin/pull/9

**Comment by cglrkn** [comment]
Hi @KevDBG 

Thank you for your suggestion. While generating message we prefer to be more generic and give more detailed information by taking into consideration all of our customer’s requirements. This plugin is open source and you can change the message depends on your requirements easily. You just need to generate jar file yourself and deploy it to your Graylog server.

Thanks
